### ISSUE TITLE
Path parsing issues

### ISSUE THREAD

**Issue by emecell** [SitePen/dojo-amd-converter#28]
System: OSX 10.8.3 using node 0.10.2

The first call of [parser.js#L13](https://github.com/SitePen/dojo-amd-converter/blob/da23dfca1fc5f29797186331c3bcb57952be6001/parse.js#L13) fails for my system since the first call does not pass in any path so I patched it locally to:

 `path = pathUtil.join(parent, path || "");` 

but then [parser.js#L54](https://github.com/SitePen/dojo-amd-converter/blob/da23dfca1fc5f29797186331c3bcb57952be6001/parse.js#L54) truncates the path wrong so I had to remove the + 1 like so: 

`path = path.slice(config.srcDir.length);`.

**Comment by dylans** [comment]
Should be pretty easy to fix... care to provide a pull request? Do you have a Dojo Foundation CLA on file?

**Comment by emecell** [comment]
Yup, I do have a CLA on file.

**Comment by emecell** [comment]
Hrm, looks like github created another issue. I'll close this one for now.
