### ISSUE TITLE
dojo.connect to aspect.after conversion error

### ISSUE THREAD

**Issue by mmaxwell** [SitePen/dojo-amd-converter#7]
It looks like the conversion from `dojo.connect` to `aspect.after` is not completely functional.

`dojo.connect(this.firstPane, '_onLoadHandler', this, 'toggleFirstPaneOverlay');`

was converted to

`aspect.after(this.firstPane, '_onLoadHandler'lang.hitch(this, 'toggleFirstPaneOverlay'), true);`

Between `_onLoadHandler` and `lang.hitch`, there should be a comma.

**Comment by csnover** [comment]
Resolved by 63c6059. Thanks @davecocoa for the PR.
